### ISSUE TITLE
Mypy: enable truthy-bool

### ISSUE THREAD

**Issue by lordgordon** [lordgordon/py-scaffolding#75]
See https://adamj.eu/tech/2022/10/24/python-type-hints-truthy-bool/:

```toml
[tool.mypy]
enable_error_code = [
    "truthy-bool",
]
```
