### ISSUE TITLE
Poetry venv in-project

### ISSUE THREAD

**Issue by lordgordon** [lordgordon/py-scaffolding#99]
For better Poetry management, we want to keep the venv in-project. Add a `poetry.toml` with:

```toml
[virtualenvs]
in-project = true
```
